### ISSUE TITLE
Add security OS

### ISSUE THREAD

**Issue by yezz123** [jubalh/awesome-os#23]
For examples we have a lot of OS with security or forensics like : 
[L4Linux](https://l4linux.org/download.shtml)
[Openwall GNU/*/Linux](https://www.openwall.com/Owl/DOWNLOAD.shtml)
[EulerOS](https://developer.huaweicloud.com/en-us/euleros/download.html?developlan=Other)
[CopperheadOS](https://copperhead.co/android/docs/install/)
[Alpine Linux](https://alpinelinux.org/downloads/)
[GrapheneOS](https://grapheneos.org/install)
[BlackArch](https://blackarch.org/downloads.html)

**Comment by jubalh** [comment]
I'm collecting different OS types for people to learn from. Mostly for people who are interested in operating system design and implementation.
I dont know all the ones you mentioned but to me it looks just like you are listing variants and distributions and not a single unique OS.

**Comment by yezz123** [comment]
Check them first and then you will see
