### ISSUE TITLE
found a twin to your awesome-os

### ISSUE THREAD

**Issue by zriyansh** [jubalh/awesome-os#49]
I can't believe this it took me so long to identify that the list I was trying to build is somewhat already built by you, awesome work man!. 

I too have an exhaustive list of Web Desktops (around 180 projects I guess) here -https://github.com/zriyansh/awesome-os

But the good news is your and my collection are different in many ways and almost non-overlapping.

Let me know what you think of it.

**Comment by jubalh** [comment]
Cool.
But yes, looks like a totally different purpose :-)
