### ISSUE TITLE
Xv6, a simple Unix-like teaching operating system

### ISSUE THREAD

**Issue by thmxv** [jubalh/awesome-os#5]
Hi, I just wanted to point to MIT's teaching os Xv6:
https://pdos.csail.mit.edu/6.828/2019/xv6.html

It comes with a book:
https://pdos.csail.mit.edu/6.828/2019/xv6/book-riscv-rev0.pdf

The latest version is for RISC-V but previous versions for x86 are also available (also with a book)

**Comment by jubalh** [comment]
Thanks for the hint @thmxv
