### ISSUE TITLE
Broken links for Embox and Cadex OS

### ISSUE THREAD

**Issue by mezantrop** [jubalh/awesome-os#65]
Everything in the subject.

**Comment by jubalh** [comment]
Would you mind sending a PR with the new links or removing the projects? Or maybe let them stay and add *broken link* or something. I'm not sure what's best.

**Comment by mezantrop** [comment]
Created pull: https://github.com/jubalh/awesome-os/pull/66

**Comment by jubalh** [comment]
Thanks
