### ISSUE TITLE
Oberon OS is missing

### ISSUE THREAD

**Issue by EdoardoLaGreca** [jubalh/awesome-os#71]
I noticed that the [Oberon operating system](https://en.wikipedia.org/wiki/Oberon_(operating_system)) from the legendary [Niklaus Wirth](https://en.wikipedia.org/wiki/Niklaus_Wirth) is missing in the list.

Please add :)

**Comment by 995qa** [comment]
~~skill issue~~

**Comment by jubalh** [comment]
http://www.oberon.ethz.ch/ and www.ethoberon.ethz.ch seem to be dead

**Comment by EdoardoLaGreca** [comment]
@jubalh HarveyOS is dead too but it's in the list...

**Comment by jubalh** [comment]
> Edit: I realized only now that you meant the website rather than the project. You could make a link to it's Wikipedia page.

I would like to link to some place where people can read the source code. In case you find it you could open a PR :)
