### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [jubalh/awesome-os#75]
Hi, I found some broken links:

- [ ] https://github.com/opencreeck/Cadex-OS-Official (file: README.md, status code: 404)
- [ ] https://collapseos.org/ (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [ ] https://mimiker.ii.uni.wroc.pl/ (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://brutal-org.netlify.app/ (file: README.md, status code: 404)
- [ ] https://dsc-kiit.github.io/project-halide/ (file: README.md, status code: 404)
- [ ] https://github.com/Kridar/KripayaOS (file: README.md, status code: 404)
- [ ] https://github.com/jdah/tetris-os (file: README.md, status code: 451)

**Comment by jubalh** [comment]
It's pretty annoying when people remove their projects :/

You could try to find the new links or add a *broken* indicator to the lines and create a PR if you want.
