### ISSUE TITLE
Add GarnOS?

### ISSUE THREAD

**Issue by Garnek0** [jubalh/awesome-os#94]
GarnOS is a hobby OS powered by a modular kernel that i've been working on. (https://github.com/Garnek0/GarnOS)

If you consider it's adequate, could you please add it to the list? I'd be really grateful :)

**Comment by jubalh** [comment]
You can create a PR and add it to the *hobby* section :)

**Comment by jubalh** [comment]
https://github.com/jubalh/awesome-os/pull/95
